---
abstract: 'An SMS::Send driver for the RedOxygen RedSMS web-to-SMS service'
author:
  - 'Craig Ringer <craig@2ndquadrant.com>'
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: SMS::Send::RedSMS
name: SMS-Send-RedSMS
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  LWP: 5.69
  SMS::Send: 1.06
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.03
